
<!-- blue bar to serate white content bg from universal footer --><span class="block-p"></span>

<footer>
        <div class="nys-global-footer">
            <div class="footer-container">
                <h3 style="color: #0073ea;">Quick Links </h3>
                <div class="footer-col">
                    <h4>About ESD</h4>
                    <ul>
                        <li><a href="http://www.esd.ny.gov" target="_blank">Empire State Development</a></li>
                        <li> <a href="https://esd.ny.gov/sites/default/files/Dashboard-2023-11.pdf"
                                target="_blank">Economic
                                Indicators Dashboard</a></li>
                        <li><a href="https://esd.ny.gov/esd-media-center/reports" target="_blank">Reports</a></li>
                        <li><a href="https://esd.ny.gov/about-us/careers" target="_blank">Careers</a></li>
                        <li> <a href="https://esd.ny.gov/doing-business-ny/requests-proposals" target="_blank">Requests
                                for
                                Proposals</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Public Information</h4>
                    <ul>
                        <li><a href="https://esd.ny.gov/esd-media-center/board-meetings" target="_blank">Board
                                Meetings</a></li>
                        <li><a href="https://esd.ny.gov/publicmeetings_notices/publicmeetings_archives.html"
                                target="_blank">Board
                                Meeting Archives</a></li>
                        <li><a href="http://esd.ny.gov/FOIL.html" target="_blank">FOIL Requests</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Help</h4>
                    <ul>
                        <li><a href="http://esd.ny.gov/privacypolicy.html#accessibility"
                                target="_blank">Accessibility</a></li>
                        <li><a href="http://esd.ny.gov/PrivacyPolicy.html" target="_blank">Privacy Policy</a></li>
                        <li><a href="https://esd.ny.gov/about-us/contact-us" target="_blank">Contact Us</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Miscellaneous</h4>
                    <ul>
                        <li> <a href="../generalResources/ESD-Agency-Organizational-Chart-2023.pdf"
                                target="_blank">Organizational
                                Chart</a></li>
                        <li> <a href="https://goer.ny.gov/anti-discrimination-investigations" target="_blank">Employee
                                Discrimination Complaint Form</a> </li>
                        <li><a href="../digitalLiaisons.asp">Digital Liaison Resources</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Affiliates</h4>
                    <ul>
                        <li><a href="http://www.iloveny.com/" target="_blank"> I LOVE NEW YORK </a></li>
                        <li><a href="https://esd.ny.gov/industries/tv-and-film/" target="_blank">NYS FILM </a></li>
                    </ul>
                </div>
                <div class="social-media"> </div>
                <!-- FOOTER CONTENT ENDS HERE -->
            </div>
        </div>
    </footer>