<!-- Include NavBar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="#">ESD Employee Intranet</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li> -->
        <li class="nav-item">
          <a class="nav-link" href="corp-employee-benefits.asp">Corp Employee Benefits</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="ear.asp">Economic Analysis & Research</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="fp.asp">Finance & Procurement</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="hr.asp">Human Resources</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="dei.asp">Diversity & Inclusion</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="legal.asp">Legal Resources</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="it.asp">IT</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="crisis-procedures.asp">Crisis Procedures</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="mrkt-branding.asp">Marketing & Branding</a>
        </li>
        <!--   
          <li class="nav-item">
            <a class="nav-link" href="https://esd.ny.gov/regions" target="_blank">Regional Offices</a>
          </li> -->

        <!-- Dropdown Template <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="sub.asp">Action</a></li>
              <li><a class="dropdown-item" href="sub.asp">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="sub.asp">Something</a></li>
            </ul>
          </li> -->

        <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
      </ul>
      <!-- Search Box <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
    </div>
  </div>
</nav>